"""empty message

Revision ID: 130e4dc44312
Revises: 6d0a172c669d
Create Date: 2025-01-04 21:32:02.421407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130e4dc44312'
down_revision = '6d0a172c669d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_main',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=75), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_main')
    # ### end Alembic commands ###
