"""Database with only movies and top_movies without unique contraint

Revision ID: 76b9ea4a08ff
Revises: 
Create Date: 2025-02-16 20:04:28.486326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b9ea4a08ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('top_movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top_movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
